---

- name: "{{ ansible_os_family }} Family"
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: "SNMPD Configuration"
  include_tasks: snmpd.yml
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat' or freebsd_bsnmp == False

- name: "BSNMPD Configuration"
  include_tasks: bsnmpd.yml
  when: ansible_facts['os_family'] == 'FreeBSD' and freebsd_bsnmp == True

