- name: Setup /etc/default/snmpd.conf
  template:
    src: etc/default/snmpd.jinja2
    dest: /etc/default/snmpd
    owner: root
    group: "{{snmpd_file_group}}"
    mode: 0644
  notify: restart snmpd
  when: ansible_os_family == 'Debian'

- name: Setup /etc/snmp/snmpd.conf
  template:
    src: etc/snmp/snmpd.jinja2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: "{{snmpd_file_group}}"
    mode: 0600
  notify: restart snmpd

- name: Enable and start SNMPD
  service:
    name: snmpd
    state: "started"
    enabled: True
  when: snmpd_enabled

- name: Disable and stop SNMPD
  service:
    name: snmpd
    state: "stopped"
    enabled: False
  when: not snmpd_enabled
