---
- name: restart snmpd
  service:
    name: snmpd
    state: restarted
  when: snmpd_enabled and ansible_os_family != 'FreeBSD'

- name: restart bsnmpd
  service:
    name: bsnmpd
    state: restarted
  when: snmpd_enabled and ansible_os_family == 'FreeBSD'

